machine:
  image: ubuntu-2004:202010-01
  docker_layer_caching: true
steps:
- checkout
- setup_node16
- install_python_requests
- run:
    command: mkdir -p /tmp/logs/test/integration/kind-olm-operator
    name: Create temporary directory for logs
- run:
    command: |
      export OPERATOR_VERSION="0.0.1-${CIRCLE_SHA1}"
      export KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=$(./scripts/circleci-jobs/setup-integration-tests.py)
      .circleci/do-exclusively --branch staging --job ${CIRCLE_JOB} npm run test:integration:kindolm:operator
    name: Operator integration tests on vanilla Kubernetes
- run:
    command: |
      ./scripts/slack/notify_failure_on_branch.py "${CIRCLE_BRANCH}" "${CIRCLE_JOB}" "${CIRCLE_BUILD_URL}" "${CIRCLE_PULL_REQUEST}" "${SLACK_WEBHOOK}"
    name: Notify Slack on failure
    when: on_fail
- store_artifacts:
    path: /tmp/logs/test/integration/kind-olm-operator
working_directory: ~/kubernetes-monitor
