machine:
  docker_layer_caching: true
  enabled: true
steps:
- checkout
- setup_node12
- install_python_requests
- run:
    command: mkdir -p /tmp/logs/test/integration/kind-olm-operator
    name: Create temporary directory for logs
- run:
    command: |
      export KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=$(./scripts/circleci-jobs/setup-integration-tests.py)
      .circleci/do-exclusively --branch staging --job ${CIRCLE_JOB} npm run test:integration:kindolm:operator
    name: Operator integration tests on plain k8s
- run:
    name: Delete Operators from Quay
    command: |
      python3 scripts/operator/delete_operators_from_quay.py
    when: always
- run:
    command: |
      ./scripts/slack/notify_failure_on_branch.py "${CIRCLE_BRANCH}" "${CIRCLE_JOB}" "${CIRCLE_BUILD_URL}" "${CIRCLE_PULL_REQUEST}" "${SLACK_WEBHOOK}"
    name: Notify Slack on failure
    when: on_fail
- store_artifacts:
    path: /tmp/logs/test/integration/kind-olm-operator
working_directory: ~/kubernetes-monitor
