#
# This file creates the deployment that runs the Kubernetes-Monitor
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-monitor
  namespace: snyk-monitor
  labels:
    app.kubernetes.io/name: snyk-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snyk-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snyk-monitor
    spec:
      containers:
      - image: snyk/kubernetes-monitor:1.25.2
        imagePullPolicy: Always
        name: snyk-monitor
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: docker-config
          readOnly: true
          mountPath: "/srv/app/.docker"
        - name: temporary-storage
          mountPath: "/var/tmp"
        env:
          - name: SNYK_INTEGRATION_ID
            valueFrom:
              secretKeyRef:
                name: snyk-monitor
                key: integrationId
          - name: SNYK_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: namespace
                optional: true
          - name: SNYK_INTEGRATION_API
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: integrationApi
                optional: true
          - name: SNYK_CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: clusterName
                optional: true
          - name: SNYK_MONITOR_VERSION
            value: 1.25.2
          - name: HOME
            value: /srv/app
        resources:
          requests:
            cpu: '250m'
            memory: '400Mi'
          limits:
            cpu: '1'
            memory: '2Gi'
        securityContext:
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      volumes:
      - name: docker-config
        secret:
          secretName: snyk-monitor
          items:
            - key: dockercfg.json
              path: config.json
      - name: temporary-storage
        emptyDir:
          sizeLimit: 50Gi
      serviceAccountName: snyk-monitor
