apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-monitor
  namespace: snyk-monitor
  labels:
    app.kubernetes.io/name: snyk-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snyk-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snyk-monitor
    spec:
      containers:
      - image: snyk/kubernetes-monitor:1.8.0
        imagePullPolicy: Always
        name: snyk-monitor
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: docker-socket-mount
          mountPath: /var/run/docker.sock
        - name: docker-config
          readOnly: true
          mountPath: "/root/.docker"
        - name: temporary-storage
          mountPath: "/snyk-monitor"
        env:
          - name: SNYK_INTEGRATION_ID
            valueFrom:
              secretKeyRef:
                name: snyk-monitor
                key: integrationId
          - name: SNYK_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: namespace
                optional: true
          - name: SNYK_INTEGRATION_API
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: integrationApi
                optional: true
          - name: SNYK_CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: clusterName
                optional: true
          - name: SNYK_STATIC_ANALYSIS
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: staticAnalysis
                optional: true
        resources:
          requests:
            cpu: '250m'
            memory: '400Mi'
          limits:
            cpu: '1'
            memory: '2Gi'
      securityContext: {}
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: docker-config
        secret:
          secretName: snyk-monitor
          defaultMode: 256
          items:
            - key: dockercfg.json
              path: config.json
      - name: temporary-storage
        emptyDir:
          sizeLimit: 20Gi
      serviceAccountName: snyk-monitor
