apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-monitor
  namespace: snyk-monitor
  labels:
    app.kubernetes.io/name: snyk-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snyk-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snyk-monitor
    spec:
      containers:
      - image: snyk/kubernetes-monitor:latest
        imagePullPolicy: Always
        name: snyk-monitor
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: docker-socket-mount
          mountPath: /var/run/docker.sock
        - name: docker-config
          readOnly: true
          mountPath: "/root/.docker"
        env:
          - name: SNYK_INTEGRATION_ID
            valueFrom:
              secretKeyRef:
                name: snyk-monitor
                key: integrationId
          - name: SNYK_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: snyk-monitor
                key: namespace
                optional: true
      securityContext: {}
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: docker-config
        secret:
          secretName: snyk-monitor
          defaultMode: 256
          items:
            - key: dockercfg.json
              path: config.json
      serviceAccountName: snyk-monitor
