apiVersion: charts.snyk.io/v1alpha1
kind: SnykMonitor
metadata:
  name: snyk-monitor
spec:
  clusterName: 'Test cluster'
  image:
    pullPolicy: Always
    repository: docker.io/snyk/kubernetes-monitor
    tag: 1.40.3
  integrationApi: ''
  monitorSecrets: snyk-monitor
  scope: Cluster
  temporaryStorageSize: 50Gi
