version: 2.1

staging_branch_only_filter: &staging_branch_only_filter
  filters:
    branches:
      only:
        - staging

master_branch_only_filter: &master_branch_only_filter
  filters:
    branches:
      only:
        - master

main_branches_filter: &main_branches_filter
  filters:
    branches:
      ignore:
        - staging
        - master

workflows:
  PR_TO_STAGING:
    jobs:
      - build_image:
          <<: *main_branches_filter
      - build_and_upload_operator:
          <<: *main_branches_filter
      - unit_tests:
          <<: *main_branches_filter
      - lint:
          <<: *main_branches_filter
      - code_formatter:
          <<: *main_branches_filter
      - system_tests:
          <<: *main_branches_filter
      - integration_tests:
          requires:
            - build_image
          <<: *main_branches_filter
      - integration_tests_helm:
          requires:
            - build_image
          <<: *main_branches_filter

  MERGE_TO_STAGING:
    jobs:
      - build_image:
          <<: *staging_branch_only_filter
      - build_and_upload_operator:
          <<: *staging_branch_only_filter
      - unit_tests:
          <<: *staging_branch_only_filter
      - system_tests:
          <<: *staging_branch_only_filter
      - integration_tests:
          requires:
            - build_image
          <<: *staging_branch_only_filter
      - integration_tests_helm:
          requires:
            - build_image
          <<: *staging_branch_only_filter
      - integration_tests_proxy:
          requires:
            - build_image
          <<: *staging_branch_only_filter
      - eks_integration_tests:
          requires:
            - build_image
          <<: *staging_branch_only_filter
      - aks_integration_tests:
          requires:
            - build_image
          <<: *staging_branch_only_filter
      - integration_tests_operator_on_k8s:
          requires:
            - build_image
            - build_and_upload_operator
          <<: *staging_branch_only_filter
      - openshift4_integration_tests:
          requires:
            - build_image
            - build_and_upload_operator
          <<: *staging_branch_only_filter
      - tag_and_push:
          requires:
            - build_image
            - build_and_upload_operator
            - unit_tests
            - system_tests
            - integration_tests
            - integration_tests_helm
            - integration_tests_proxy
          <<: *staging_branch_only_filter
      - deploy_to_dev:
          requires:
            - tag_and_push
          <<: *staging_branch_only_filter
      - deploy_to_sysdig_integration_cluster:
          requires:
            - tag_and_push
          <<: *staging_branch_only_filter

  MERGE_TO_MASTER:
    jobs:
      - publish:
          <<: *master_branch_only_filter
      - deploy_to_prod:
          requires:
            - publish
          <<: *master_branch_only_filter

  NIGHTLY:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - operator_upgrade_tests

  MONTHLY:
    triggers:
      - schedule:
          cron: "0 5 3 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - operator_upgrade_tests
      # - push_operator_to_embedded_community_operators:
      #     requires:
      #       - operator_upgrade_tests
      # - push_operator_to_community_operators:
      #     requires:
      #       - operator_upgrade_tests

  MANUAL_OPENSHIFT_RELEASE:
    jobs:
      - hold:
          <<: *master_branch_only_filter
          type: approval
      - operator_upgrade_tests:
          <<: *master_branch_only_filter
          requires:
            - hold
      # - sync_embedded_community_operators_with_snyk_fork:
      #     <<: *master_branch_only_filter
      #     requires:
      #       - operator_upgrade_tests
      # - push_operator_to_embedded_community_operators:
      #     <<: *master_branch_only_filter
      #     requires:
      #       - sync_embedded_community_operators_with_snyk_fork
      # - sync_community_operators_with_snyk_fork:
      #     <<: *master_branch_only_filter
      #     requires:
      #       - push_operator_to_embedded_community_operators
      # - push_operator_to_community_operators:
      #     <<: *master_branch_only_filter
      #     requires:
      #       - sync_community_operators_with_snyk_fork
